### ISSUE TITLE
Bachome - AI or AV without thermostat oder cooling, like only outsidetempreatur

### ISSUE THREAD

**Issue by koerby** [Caserage/bachome#12]
Hi,

at first thanks for the fix, the switch works great! I wait a long time for a bacnet homebridge plugin, thank you very much!

Give it an option for only AI oder AV? Like outsidetempretaur or something else? I have two bacnet controller for my heating system an now i want to show the temperaturs in homekit or set the setpoints.

**Comment by koerby** [comment]
I have on controller with DeviceID = 1 , there the switch works fine and i have another  one with DeviceID= 2100227, there the switch doesn't work, i think i musst be config the device id? any idea?

**Comment by koerby** [comment]
Hi again,
i have programm my bacnet controller new with ai's and av's for the thermostate object, give it a change to make the "currentHeatingCoolingState": "AI:20" also with an AV?

**Comment by Apsysikal** [comment]
Hi

Glad to hear it works :)
I'll look into adding the option for standalone objects like a sensor. The object variety with AIs and AVs, as well as BIs and BVs is also a thing I'd like to add.

Under the hood I use [BACstack](https://github.com/fh1ch/node-bacstack), which, according to the official documentation only uses the IP address for communication. There is no way for me to specify a device ID in the library. Maybe if you had some logs I could look into that but at first glance my hands are tied in the device ID problem.

**Comment by Apsysikal** [comment]
Update 1.4.0 brings functionality for temperature sensors. You can use AI, AV, AO objects with the new accessory.
