### ISSUE TITLE
No Communication in HomeKit

### ISSUE THREAD

**Issue by koerby** [Caserage/bachome#13]
The objects in HomeKit are not reachable after node update i think...

Jun 22 09:02:02 homebridge homebridge[6067]:     at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-bachome/node_modules/bacstack/lib/client.js:75:
Jun 22 09:02:02 homebridge homebridge[6067]:     at listOnTimeout (internal/timers.js:557:17)
Jun 22 09:02:02 homebridge homebridge[6067]:     at processTimers (internal/timers.js:500:7)
Jun 22 09:02:02 homebridge homebridge[6067]: (node:6067) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwi
Jun 22 09:02:02 homebridge homebridge[6067]: (node:6067) UnhandledPromiseRejectionWarning: Error: ERR_TIMEOUT
Jun 22 09:02:02 homebridge homebridge[6067]:     at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-bachome/node_modules/bacstack/lib/client.js:75:
Jun 22 09:02:02 homebridge homebridge[6067]:     at listOnTimeout (internal/timers.js:557:17)
Jun 22 09:02:02 homebridge homebridge[6067]:     at processTimers (internal/timers.js:500:7)

**Comment by Apsysikal** [comment]
I'm not able to reproduce the issue currently. I've updated homebridge and node version dependencies for the plugin. This will be in the next version update.

**Comment by Apsysikal** [comment]
There is another open issue regarding this problem.
The issue is: #15
