### ISSUE TITLE
Adding single points.

### ISSUE THREAD

**Issue by OrangeRAZ** [Caserage/bachome#14]
i was looking for a way to add like a single temperature sensor or KWH Meter analog value. do you know if this is possible with the current accessories you have?

**Comment by Apsysikal** [comment]
I have written the code for an additional accessory (temperature sensor), but it's not yet released to npm.
You could download the source code and try it if you want. Otherwise it will be in the next bigger version update.

**Comment by Apsysikal** [comment]
In the current version (1.4.2) you are able to add a temperature sensor as a single accessory. I'll have to dive deeper into which accessories are available. For the time the temperature sensor is the one you'll be able to use.

**Comment by OrangeRAZ** [comment]
Thanks, I got the update and it works great!

**Comment by Apsysikal** [comment]
Nice! Im pleased to hear that.
