### ISSUE TITLE
No Command to BACnet Network

### ISSUE THREAD

**Issue by raubuchs** [Caserage/bachome#33]
Hello
First of all thanks for the implementation of the plugin.
I'm testing it at the moment, but i'm struggeling to get it running.
The integration into Homebridge was no problem, Also the Switch button are in my Home App.
Unfortunatelly no command is "broadcasted" into the network from my iPhone.
I'm using YABE as Bacnet Explorer and nothing changes inside.
Do you have a clue wat this could be.
BR
Sebastian

**Comment by Apsysikal** [comment]
Hey Sebastian

Thank you for opening this issue here.

Your iPhone won't send any BACnet commands to the network. The BACnet commands are always executed from where the plugin is running aka. you homebridge device.
For this reason I would like to know if your homebridge device (a raspberrypi or similar) is able to connect to your BACnet device?

Best regards
Ben

**Comment by raubuchs** [comment]
Hi Ben
Could you give me a hint, how to check if the homebridge (a raspberry) is able to connect to my devices?
BR
Sebastian

**Comment by raubuchs** [comment]
Ok, I've now tested the connection with wireguard. The Homebridge Server isn't subscribing to the BACnet Objects. Also he is not sending messages over the network.

**Comment by Apsysikal** [comment]
I'd suggest checking the logs. If you don't have a connection to the device(s) there are usually timeout errors output to the console. Do you use homebridge-ui?

Also: The plugin does not subscribe to changes (COV) but relies on polling to refresh values.

**Comment by raubuchs** [comment]
So in homebridge-ui there are no errors inside the logs.

**Comment by Apsysikal** [comment]
I currently don‘t know what else could be the problem. I think homebridge-ui does not show logs in the ui by default, but I can't tell you how to fix that.
Could you provide your `config.json` contents? I can check for config-errors but currently I‘m not sure what could be the problem.

**Comment by raubuchs** [comment]
Sure
`{
    "bridge": {
        "name": "Homebridge E469",
        "username": "xx:xx:xx:xx:xx:xx",
        "port": 12345,
        "pin": "111-22-333",
        "advertiser": "avahi",
        "bind": [
            "eth0"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "BAChome Dynamic Platform",
            "port": 47808,
            "switch": [
                {
                    "name": "Lichtband 1.1",
                    "manufacturer": "A",
                    "model": "Lichtband",
                    "serial": "AYS-CXT-AFW",
                    "ipAddress": "10.10.10.20",
                    "stateObject": "BO:0"
                },
                {
                    "name": "Lichtband 1.2",
                    "manufacturer": "A",
                    "model": "Lichtband",
                    "serial": "WQJ-WIO-VMU",
                    "ipAddress": "10.10.10.20",
                    "stateObject": "BO:1"
                },
                {
                    "name": "Lichtband 1.3",
                    "manufacturer": "A",
                    "model": "Lichtband",
                    "serial": "NPC-WVS-BAL",
                    "ipAddress": "10.10.10.20",
                    "stateObject": "BO:2"
                },
                {
                    "name": "Lichtband 2.1",
                    "manufacturer": "A",
                    "model": "Lichtband",
                    "serial": "WIL-JPR-YJK",
                    "ipAddress": "10.10.10.20",
                    "stateObject": "BO:5"
                },
                {
                    "name": "Lichtband 2.2",
                    "manufacturer": "A",
                    "model": "Lichtband",
                    "serial": "OTR-FNX-HQN",
                    "ipAddress": "10.10.10.20",
                    "stateObject": "BO:6"
                },
                {
                    "name": "Lichtband 2.3",
                    "manufacturer": "A",
                    "model": "Lichtband",
                    "serial": "IYD-DCE-XTX",
                    "ipAddress": "10.10.10.20",
                    "stateObject": "BO:7"
                }
            ],
            "platform": "bachome"
        }
    ]
}`

**Comment by raubuchs** [comment]
> Sure `{ "bridge": { "name": "Homebridge E469", "username": "xx:xx:xx:xx:xx:xx", "port": 12345, "pin": "111-22-333", "advertiser": "avahi", "bind": [ "eth0" ] }, "accessories": [], "platforms": [ { "name": "Config", "port": 8581, "platform": "config" }, { "name": "BAChome Dynamic Platform", "port": 47808, "switch": [ { "name": "Lichtband 1.1", "manufacturer": "A", "model": "Lichtband", "serial": "AYS-CXT-AFW", "ipAddress": "10.10.10.20", "stateObject": "BO:0" }, { "name": "Lichtband 1.2", "manufacturer": "A", "model": "Lichtband", "serial": "WQJ-WIO-VMU", "ipAddress": "10.10.10.20", "stateObject": "BO:1" }, { "name": "Lichtband 1.3", "manufacturer": "A", "model": "Lichtband", "serial": "NPC-WVS-BAL", "ipAddress": "10.10.10.20", "stateObject": "BO:2" }, { "name": "Lichtband 2.1", "manufacturer": "A", "model": "Lichtband", "serial": "WIL-JPR-YJK", "ipAddress": "10.10.10.20", "stateObject": "BO:5" }, { "name": "Lichtband 2.2", "manufacturer": "A", "model": "Lichtband", "serial": "OTR-FNX-HQN", "ipAddress": "10.10.10.20", "stateObject": "BO:6" }, { "name": "Lichtband 2.3", "manufacturer": "A", "model": "Lichtband", "serial": "IYD-DCE-XTX", "ipAddress": "10.10.10.20", "stateObject": "BO:7" } ], "platform": "bachome" } ] }`

Hello
Is there something new about this?

**Comment by raubuchs** [comment]
Hello
I'm not sure what happened, but i've restarted the complete project and rebuild my complete homebridge installation including bachome and now everything works.
Perhaps there was an issue from the raspberry.
Really strange
But thanks for the investigations you have done.
BR
Seb

**Comment by Apsysikal** [comment]
Your config looked ok, so I didn’t know what to do. Nice to hear it’s working now - Hope you enjoy.
